# Generated by Django 4.0 on 2021-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_badge', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
