# Generated by Django 4.0 on 2021-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(null=True, related_name='employees', to='NotifyMeModels.Employee'),
        ),
    ]
