# Generated by Django 4.0 on 2021-12-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0002_alter_group_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='NotifyMeModels.Employee'),
        ),
    ]
