# Generated by Django 4.0 on 2021-12-16 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0003_alter_group_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 0, 2, 50, 379310, tzinfo=utc))),
                ('message_content', models.TextField()),
                ('number_seen', models.IntegerField(default=0)),
                ('stat_message', models.CharField(choices=[('R', 'Red'), ('O', 'Orande'), ('G', 'Green')], default='R', max_length=1)),
                ('message_destinations', models.ManyToManyField(related_name='destinations', to='NotifyMeModels.Employee')),
            ],
        ),
    ]
