# Generated by Django 4.0 on 2021-12-16 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 0, 7, 6, 418762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='stat_message',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
