# Generated by Django 4.0 on 2021-12-16 00:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0005_alter_message_date_sent_alter_message_stat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 0, 11, 29, 374481, tzinfo=utc)),
        ),
    ]
