# Generated by Django 4.0 on 2021-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0006_alter_message_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='number_seen',
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(related_name='employees_seen_message', to='NotifyMeModels.Employee'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(),
        ),
    ]
