# Generated by Django 4.0 on 2021-12-16 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0007_remove_message_number_seen_message_seen_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 15, 35, 49, 500997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, default=[], related_name='employees_seen_message', to='NotifyMeModels.Employee'),
        ),
    ]
