# Generated by Django 4.0 on 2021-12-16 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0008_alter_message_date_sent_alter_message_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 15, 37, 55, 601192, tzinfo=utc)),
        ),
    ]
