# Generated by Django 4.0 on 2021-12-23 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMeModels', '0009_alter_message_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 15, 49, 24, 248561, tzinfo=utc)),
        ),
    ]
